"""Hand-maintained mapping of proto field names to CLI flags.

The code generator merges this table into _field_meta.py.
Fields not listed here are assumed to have no CLI equivalent.
"""

# (message_name, field_name) -> (cli_flag, cli_supported)
CLI_FLAGS: dict[tuple[str, str], tuple[str, bool]] = {
    ("NsJailConfig", "name"): ("--name", True),
    ("NsJailConfig", "hostname"): ("--hostname", True),
    ("NsJailConfig", "cwd"): ("--cwd", True),
    ("NsJailConfig", "port"): ("--port", True),
    ("NsJailConfig", "bindhost"): ("--bindhost", True),
    ("NsJailConfig", "max_conns"): ("--max_conns", True),
    ("NsJailConfig", "max_conns_per_ip"): ("--max_conns_per_ip", True),
    ("NsJailConfig", "time_limit"): ("--time_limit", True),
    ("NsJailConfig", "daemon"): ("--daemon", True),
    ("NsJailConfig", "max_cpus"): ("--max_cpus", True),
    ("NsJailConfig", "nice_level"): ("--nice_level", True),
    ("NsJailConfig", "keep_env"): ("--keep_env", True),
    ("NsJailConfig", "envar"): ("--env", True),
    ("NsJailConfig", "silent"): ("--silent", True),
    ("NsJailConfig", "skip_setsid"): ("--skip_setsid", True),
    ("NsJailConfig", "stderr_to_null"): ("--stderr_to_null", True),
    ("NsJailConfig", "pass_fd"): ("--pass_fd", True),
    ("NsJailConfig", "disable_no_new_privs"): ("--disable_no_new_privs", True),
    ("NsJailConfig", "forward_signals"): ("--forward_signals", True),
    ("NsJailConfig", "disable_tsc"): ("--disable_tsc", True),
    ("NsJailConfig", "oom_score_adj"): ("--oom_score_adj", True),
    ("NsJailConfig", "log_fd"): ("--log_fd", True),
    ("NsJailConfig", "log_file"): ("--log", True),
    ("NsJailConfig", "keep_caps"): ("--keep_caps", True),
    ("NsJailConfig", "cap"): ("--cap", True),
    ("NsJailConfig", "rlimit_as"): ("--rlimit_as", True),
    ("NsJailConfig", "rlimit_core"): ("--rlimit_core", True),
    ("NsJailConfig", "rlimit_cpu"): ("--rlimit_cpu", True),
    ("NsJailConfig", "rlimit_fsize"): ("--rlimit_fsize", True),
    ("NsJailConfig", "rlimit_nofile"): ("--rlimit_nofile", True),
    ("NsJailConfig", "rlimit_nproc"): ("--rlimit_nproc", True),
    ("NsJailConfig", "rlimit_stack"): ("--rlimit_stack", True),
    ("NsJailConfig", "disable_rl"): ("--disable_rl", True),
    ("NsJailConfig", "clone_newnet"): (None, True),
    ("NsJailConfig", "clone_newuser"): (None, True),
    ("NsJailConfig", "clone_newns"): (None, True),
    ("NsJailConfig", "clone_newpid"): (None, True),
    ("NsJailConfig", "clone_newipc"): (None, True),
    ("NsJailConfig", "clone_newuts"): (None, True),
    ("NsJailConfig", "clone_newcgroup"): (None, True),
    ("NsJailConfig", "clone_newtime"): (None, True),
    ("NsJailConfig", "uidmap"): ("--uid_mapping", True),
    ("NsJailConfig", "gidmap"): ("--gid_mapping", True),
    ("NsJailConfig", "mount_proc"): ("--mount_proc", True),
    ("NsJailConfig", "no_pivotroot"): ("--no_pivotroot", True),
    ("NsJailConfig", "seccomp_policy_file"): ("--seccomp_policy", True),
    ("NsJailConfig", "seccomp_string"): ("--seccomp_string", True),
    ("NsJailConfig", "seccomp_log"): ("--seccomp_log", True),
    ("NsJailConfig", "cgroup_mem_max"): ("--cgroup_mem_max", True),
    ("NsJailConfig", "cgroup_mem_memsw_max"): ("--cgroup_mem_memsw_max", True),
    ("NsJailConfig", "cgroup_mem_swap_max"): ("--cgroup_mem_swap_max", True),
    ("NsJailConfig", "cgroup_pids_max"): ("--cgroup_pids_max", True),
    ("NsJailConfig", "cgroup_net_cls_classid"): ("--cgroup_net_cls_classid", True),
    ("NsJailConfig", "cgroup_cpu_ms_per_sec"): ("--cgroup_cpu_ms_per_sec", True),
    ("NsJailConfig", "use_cgroupv2"): ("--use_cgroupv2", True),
    ("NsJailConfig", "detect_cgroupv2"): ("--detect_cgroupv2", True),
    ("NsJailConfig", "iface_no_lo"): ("--iface_no_lo", True),
    ("NsJailConfig", "iface_own"): ("--iface_own", True),
    ("NsJailConfig", "macvlan_iface"): ("--macvlan_iface", True),
    ("NsJailConfig", "macvlan_vs_ip"): ("--macvlan_vs_ip", True),
    ("NsJailConfig", "macvlan_vs_nm"): ("--macvlan_vs_nm", True),
    ("NsJailConfig", "macvlan_vs_gw"): ("--macvlan_vs_gw", True),
    ("NsJailConfig", "macvlan_vs_ma"): ("--macvlan_vs_ma", True),
    ("NsJailConfig", "macvlan_vs_mo"): ("--macvlan_vs_mo", True),
}
